version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - edutech-network

  backend:
    build:
      context: ./server
    image: mubashir15700/edutech-backend:latest
    container_name: edutech-backend
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - edutech-network

  frontend:
    build:
      context: ./client
      args:
        VITE_BACKEND_URL: http://localhost:3000/api
    image: mubashir15700/edutech-frontend:latest
    container_name: edutech-frontend
    ports:
      - "5173:80"
    env_file:
      - ./client/.env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - edutech-network

volumes:
  redis_data:

networks:
  edutech-network:
    driver: bridge
